services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data
    restart: unless-stopped
volumes:
  mongodb_data:
